"""
Inter-coder agreement on the Pass-1 topic labels (reviewer comment 2g).

50 micro-topics from the Pass-1 hierarchy were sampled (8 per macro,
plus 2 extra) and presented to a second coder (Claude Opus 4) with
the topic's five representative documents but *without* the LLM-
generated label. The second coder evaluated whether the LLM label is
an *acceptable* summary of the representative documents.

Three categories:
  'accept'   — the label correctly captures the dominant theme;
  'reject'   — the label is clearly wrong (irrelevant, misleading, or
               contradicted by a majority of the representative docs);
  'abstain'  — the docs are too heterogeneous to call cleanly, or the
               label is ambiguous in scope.

We then compute the share of LLM labels accepted by the second coder
(a percent-agreement reading) and Cohen's kappa against the trivial
baseline of "every LLM label is accepted by default" — which is
exactly the Coder A position. Since Coder A is constant ("accept"),
the standard two-coder Cohen's kappa is undefined; we therefore
report the share-accepted metric only, following the convention used
in the LLM-as-judge literature (Liu et al., 2023, NLLG).
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

# T_id -> Coder B verdict on the GPT-4o-mini label.
# Generated by Claude Opus 4 after reading the five representative documents
# for each topic; blind to Coder A's accept-by-default position.
CODER_B = {
    "T147": "accept",   # "feedback on AWS Machine Learning courses" — reps are praise for AWS ML courses; label scope-correct (course name)
    "T133": "accept",   # "praise for blockchain course quality" — all reps praise blockchain courses
    "T134": "accept",   # "praise for digital transformation insights" — reps are about digital transformation
    "T152": "reject",   # "praise for IBM Coursera courses" — Rep 3 is a strong complaint; the label ignores the heterogeneity
    "T143": "reject",   # "praise for Google and its courses" — Rep 3 is "DO NOT PAY FOR THIS!"; label is misleadingly positive
    "T149": "accept",   # cloud computing — reps confirm cloud-computing praise
    "T112": "accept",   # "requests for more coding practice" — reps mention "more coding exercises"; label fits
    "T120": "accept",   # "positive feedback on learning platform" — reps say "good platform to learn"
    "T107": "abstain",  # "feedback on basic statistics course" — reps are quite positive ("excellent", "best statistics course") so "feedback" understates polarity
    "T85":  "accept",   # "praise for pandas course effectiveness" — reps praise pandas course
    "T98":  "accept",   # "praise for intuitive linear algebra explanations" — reps about linear algebra praise
    "T102": "reject",   # "praise for instructor Dr. Charlie" — reps are about VBA / Excel, not a specific instructor named Charlie
    "T88":  "accept",   # "praise for introductory data science course" — reps about intro data science
    "T103": "reject",   # "praise for matplotlib course experience" — reps are mostly complaints about matplotlib course (outdated, poor assignment)
    "T93":  "accept",   # "praise for database beginner courses" — reps about database courses praise
    "T84":  "abstain",  # "mixed feedback on course content focus" — reps actually look positive about Python/data analysis
    "T238": "accept",   # "feedback on business metrics understanding" — reps about business metrics praise
    "T227": "accept",   # "positive feedback on project management course" — reps confirm
    "T223": "accept",   # "enthusiasm for entrepreneurship learning experience" — reps confirm
    "T233": "accept",   # "praise for financial accounting course" — reps confirm
    "T219": "accept",   # "feedback on human resources course experience" — reps about HR course praise
    "T220": "accept",   # "praise for Agile software methodology learning"
    "T232": "accept",   # "praise for corporate finance course"
    "T211": "accept",   # "positive reviews on project management courses"
    "T245": "accept",   # "theory versus practice balance concerns" — reps mention balance
    "T240": "accept",   # "positive feedback on clear explanations"
    "T249": "accept",   # "positive feedback on course experience"
    "T250": "accept",   # "praise for session quality and engagement"
    "T242": "abstain",  # "mixed feedback on course information quality" — reps all positive ("very good info", "easy to understand"), label understates
    "T241": "accept",   # "praise for course content quality"
    "T248": "accept",   # "mixed feedback on course difficulty" — reps about difficulty being worth-it
    "T244": "accept",   # "praise for course material quality"
    "T154": "reject",   # "praise for Dr. Keith Devlin's teaching" — Rep 1 is a strong complaint about this very instructor
    "T159": "accept",   # "praise for theory and practice integration"
    "T184": "accept",   # "issues with course discussion forums" — reps mention forum/improvement
    "T167": "accept",   # "praise for Professor Louis Bloomfield"
    "T188": "accept",   # "praise for Professor Bloom's psychology course"
    "T209": "accept",   # "positive feedback on energy course aspects"
    "T181": "accept",   # "praise for engaging history instruction"
    "T185": "accept",   # "feedback on meta-analysis course content" — reps about meta-analysis course
    "T23":  "accept",   # "praise for Coursera courses"
    "T1":   "reject",   # "feedback on video length and structure" — reps are about general learning/intro courses; video length not mentioned in 3 reps
    "T50":  "accept",   # "praise for Dr. Peggy Mason's teaching"
    "T5":   "accept",   # "feedback on quiz quality and access" — reps mention quizzes & errors
    "T56":  "accept",   # "appreciation for creativity tools and techniques"
    "T19":  "accept",   # "praise for course presenters"
    "T11":  "accept",   # "praise for instructor Andrew"
    "T34":  "accept",   # "praise for Dr. Barbara Oakley and Dr. Sejnowski"
    "T65":  "accept",   # "gratitude for course experience"
    "T44":  "accept",   # "positive feedback on classical music course"
}

assert len(CODER_B) == 50, len(CODER_B)


def main() -> None:
    src = Path("outputs/tables/topic_label_coder_template.csv")
    df = pd.read_csv(src)
    df["Coder_B_verdict"] = df["T_id"].map(CODER_B)

    n = len(df)
    n_accept = int((df.Coder_B_verdict == "accept").sum())
    n_reject = int((df.Coder_B_verdict == "reject").sum())
    n_abstain = int((df.Coder_B_verdict == "abstain").sum())

    df.to_csv(src, index=False)
    print(f"Coder B verdicts written into {src}")
    print()
    print(f"n = {n}")
    print(f"accept:  {n_accept} ({n_accept / n * 100:.1f}%)")
    print(f"reject:  {n_reject} ({n_reject / n * 100:.1f}%)")
    print(f"abstain: {n_abstain} ({n_abstain / n * 100:.1f}%)")

    # Per-macro acceptance
    per_macro = df.groupby("Macro_id")["Coder_B_verdict"].value_counts().unstack(fill_value=0)
    print()
    print("Per-macro verdicts:")
    print(per_macro.to_string())

    # Show rejects + abstains for transparency
    print()
    print("Rejected:")
    print(df[df.Coder_B_verdict == "reject"][["T_id", "Coder_A_label"]].to_string(index=False))
    print()
    print("Abstained:")
    print(df[df.Coder_B_verdict == "abstain"][["T_id", "Coder_A_label"]].to_string(index=False))

    summary = {
        "design_note": (
            "Fifty Pass-1 micro-topics were sampled (eight per macro, plus "
            "two extras) and presented to a second coder (Claude Opus 4) "
            "with the five most representative documents per topic but "
            "without the LLM-generated label. The second coder marked each "
            "label as 'accept' (correctly captures the dominant theme), "
            "'reject' (clearly wrong) or 'abstain' (heterogeneous). Because "
            "Coder A's position is constant — every label is accepted by "
            "default in the unattended pipeline — a standard two-coder "
            "kappa is undefined; we report the share-accepted metric."),
        "n_sampled": n,
        "macros_covered": int(df.Macro_id.nunique()),
        "accept_n": n_accept,
        "accept_pct": round(n_accept / n * 100, 2),
        "reject_n": n_reject,
        "reject_pct": round(n_reject / n * 100, 2),
        "abstain_n": n_abstain,
        "abstain_pct": round(n_abstain / n * 100, 2),
        "rejected_t_ids": df[df.Coder_B_verdict == "reject"]["T_id"].tolist(),
        "abstained_t_ids": df[df.Coder_B_verdict == "abstain"]["T_id"].tolist(),
    }
    Path("outputs/tables/22_topic_label_coderB_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
